# coding: utf-8

"""
    Combined API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.employee_api import EmployeeApi


class TestEmployeeApi(unittest.TestCase):
    """EmployeeApi unit test stubs"""

    def setUp(self) -> None:
        self.api = EmployeeApi()

    def tearDown(self) -> None:
        pass

    def test_employee_get(self) -> None:
        """Test case for employee_get

        """
        pass

    def test_employee_id_delete(self) -> None:
        """Test case for employee_id_delete

        """
        pass

    def test_employee_id_get(self) -> None:
        """Test case for employee_id_get

        """
        pass

    def test_employee_id_put(self) -> None:
        """Test case for employee_id_put

        """
        pass

    def test_employee_post(self) -> None:
        """Test case for employee_post

        """
        pass


if __name__ == '__main__':
    unittest.main()
