# coding: utf-8

"""
    Combined API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from openapi_client.models.date_only import DateOnly

class TestDateOnly(unittest.TestCase):
    """DateOnly unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> DateOnly:
        """Test DateOnly
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `DateOnly`
        """
        model = DateOnly()
        if include_optional:
            return DateOnly(
                year = 56,
                month = 56,
                day = 56,
                day_of_week = 0,
                day_of_year = 56,
                day_number = 56
            )
        else:
            return DateOnly(
        )
        """

    def testDateOnly(self):
        """Test DateOnly"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
