# coding: utf-8

# flake8: noqa
"""
    Combined API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


# import models into model package
from openapi_client.models.contact import Contact
from openapi_client.models.date_only import DateOnly
from openapi_client.models.day_of_week import DayOfWeek
from openapi_client.models.employee import Employee
